# (c) Dito Technologies LLC. Auto-generated. Do not modify directly.
# hash: 335b05736deb9bcec05ac59ccbe0e373f0e1937d96d9fb5a7354a40fb179ad83
# generated from templates/py_brushcue_stubs.jinja

from __future__ import annotations

class Context:
    def __new__(cls) -> Context: ...

class TypeDefinition:
    name: str
    display_name: str
    description: str

class NodeDefinitionInput:
    name: str
    description: str
    input_type: TypeDefinition

class NodeDefinition:
    node_type_id: int
    name: str
    display_name: str
    description: str
    output_type: TypeDefinition
    inputs: list[NodeDefinitionInput]

class ImageRecipe:
    def size(self) -> tuple[int, int] | None: ...
    def to_image_bytes(self, context: Context) -> bytes: ...

class MovieRecipe:
    def duration(self) -> float: ...
    def export_animated_web_p(self, context: Context, frame_rate: int) -> bytes: ...
    def export_gif(self, context: Context, frame_rate: int) -> bytes: ...

class Type:
    def type_definition(self) -> TypeDefinition: ...
    def type_name(self) -> str: ...
    def as_bool(self) -> bool: ...
    def as_int(self) -> int: ...
    def as_float(self) -> float: ...
    def as_string(self) -> str: ...
    def as_float_list(self) -> list[float]: ...
    def as_int_list(self) -> list[int]: ...
    def as_composition(self) -> ImageRecipe: ...
    def as_sequence(self) -> MovieRecipe: ...
    def as_vector2i(self) -> tuple[int, int]: ...
    def as_vector2f(self) -> tuple[float, float]: ...
    def as_rgba_color(self) -> tuple[float, float, float, float]: ...

class Graph:
    def persistent_id(self) -> int: ...
    def revision_id(self) -> int: ...
    def node_definition(self) -> NodeDefinition: ...
    def input_graphs(self) -> list[Graph]: ...
    def replacing(self, graph_id: int, graph: Graph) -> Graph: ...
    def removing(self, graph_id: int) -> Graph: ...
    def find(self, graph_id: int) -> Graph | None: ...
    def generate_ipynb_script(self) -> str: ...
    def execute(self, context: Context) -> Type: ...

class Project:
    def __new__(cls) -> Project: ...
    def add_graph(self, graph: Graph) -> Project: ...
    def all_nodes(self) -> list[Graph]: ...
    def lookup(self, graph_id: int) -> Graph | None: ...
    def serialize(self, context: Context) -> bytes: ...
    def execute(self, context: Context, graph_id: int) -> Type: ...
    @staticmethod
    def deserialize(context: Context, data: bytes) -> Project: ...
    def execute_tool(self, tool_name: str, input_json: str, id_mapper: IDMapper, context: Context) -> tuple[str, Project]: ...
    def mcp_project(self, id_mapper: IDMapper) -> str: ...

class IDMapper:
    def __new__(cls) -> IDMapper: ...
    def get_or_insert(self, graph_id: int) -> int: ...
    def resolve(self, short_id: int) -> int: ...
    def serialize_json(self) -> str: ...
    @staticmethod
    def deserialize_json(json: str) -> IDMapper: ...

def all_tools() -> str: ...
def mcp_prompt() -> str: ...
def byte_list_constant_internal(values: bytes) -> Graph: ...
def point2i_list_constant_internal(values: list[tuple[int, int]]) -> Graph: ...
def int_constant_internal(value: int) -> Graph: ...
def float_constant_internal(value: float) -> Graph: ...
def string_constant_internal(value: str) -> Graph: ...
def bool_constant_internal(value: bool) -> Graph: ...
def r_g_b_a_color_constant_internal(r: float, g: float, b: float, a: float) -> Graph: ...
def r_g_b_color_constant_internal(r: float, g: float, b: float) -> Graph: ...
def vector2i_constant_internal(x: int, y: int) -> Graph: ...
def vector2f_constant_internal(x: float, y: float) -> Graph: ...


def abs_internal(number: Graph) -> Graph: ...

def and_internal(bool1: Graph, bool2: Graph) -> Graph: ...

def bool_add_to_dictionary_internal(dictionary: Graph, key: Graph, value: Graph) -> Graph: ...

def bool_if_internal(bool: Graph, input_1: Graph, input_2: Graph) -> Graph: ...

def bounds2f_from_x_y_width_height_internal(x: Graph, y: Graph, width: Graph, height: Graph) -> Graph: ...

def bounds2f_height_internal(bounds: Graph) -> Graph: ...

def bounds2f_min_x_internal(bounds: Graph) -> Graph: ...

def bounds2f_min_y_internal(bounds: Graph) -> Graph: ...

def bounds2f_width_internal(bounds: Graph) -> Graph: ...

def bounds2i_from_x_y_width_height_internal(x: Graph, y: Graph, width: Graph, height: Graph) -> Graph: ...

def brush_solid_internal(color: Graph, radius: Graph) -> Graph: ...

def byte_list_from_u_r_l_internal(url: Graph) -> Graph: ...

def color_profile_b_t709_internal() -> Graph: ...

def color_profile_ok_lab_a_internal() -> Graph: ...

def color_profile_p3_internal() -> Graph: ...

def color_profile_p_n_g_s_r_g_b_internal() -> Graph: ...

def color_profile_s_r_g_b_internal() -> Graph: ...

def color_profile_s_r_g_b_linear_internal() -> Graph: ...

def color_profile_x_y_z_internal() -> Graph: ...

def composition_absolute_value_internal(image: Graph) -> Graph: ...

def composition_blend_add_internal(foreground: Graph, background: Graph, foreground_transform: Graph) -> Graph: ...

def composition_blend_alpha_internal(foreground: Graph, background: Graph, foreground_transform: Graph) -> Graph: ...

def composition_blend_max_internal(foreground: Graph, background: Graph, foreground_transform: Graph) -> Graph: ...

def composition_blend_min_internal(foreground: Graph, background: Graph, foreground_transform: Graph) -> Graph: ...

def composition_blend_multiply_internal(foreground: Graph, background: Graph, foreground_transform: Graph) -> Graph: ...

def composition_blend_stencil_internal(foreground: Graph, background: Graph, foreground_transform: Graph) -> Graph: ...

def composition_blend_subtract_internal(foreground: Graph, background: Graph, foreground_transform: Graph) -> Graph: ...

def composition_bloom_internal(composition: Graph, threshold: Graph, sigma: Graph, intensity: Graph) -> Graph: ...

def composition_bounds_internal(composition: Graph) -> Graph: ...

def composition_box_blur_internal(composition: Graph, dimension: Graph) -> Graph: ...

def composition_brightness_adjust_internal(composition: Graph, scale: Graph) -> Graph: ...

def composition_chroma_offset_internal(composition: Graph, offset: Graph) -> Graph: ...

def composition_color_convert_internal(composition: Graph, color_profile: Graph) -> Graph: ...

def composition_color_invert_internal(composition: Graph) -> Graph: ...

def composition_color_profile_internal(composition: Graph) -> Graph: ...

def composition_color_threshold_internal(composition: Graph, threshold: Graph) -> Graph: ...

def composition_color_transformer_shader_internal(composition: Graph, function_body: Graph, helpers: Graph, input_color_profile: Graph, output_color_profile: Graph, inputs: Graph) -> Graph: ...

def composition_contrast_adjustment_internal(composition: Graph, contrast: Graph) -> Graph: ...

def composition_convolution_internal(composition: Graph, kernel: Graph, kernel_width: Graph, kernel_height: Graph) -> Graph: ...

def composition_crop_internal(composition: Graph, rect: Graph) -> Graph: ...

def composition_film_grain_internal(composition: Graph, grain_strength: Graph, fine_grain_frequency: Graph, fine_weight: Graph, medium_grain_frequency: Graph, medium_weight: Graph, high_grain_frequency: Graph, high_weight: Graph) -> Graph: ...

def composition_flip_horizontal_internal(composition: Graph) -> Graph: ...

def composition_flip_vertical_internal(composition: Graph) -> Graph: ...

def composition_from_asset_internal(asset_id: Graph) -> Graph: ...

def composition_from_image_internal(image: Graph) -> Graph: ...

def composition_gaussian_blur_internal(composition: Graph, sigma: Graph) -> Graph: ...

def composition_grayscale_internal(composition: Graph) -> Graph: ...

def composition_halftone_internal(composition: Graph, pixel_size: Graph, foreground_color: Graph, background_color: Graph) -> Graph: ...

def composition_if_internal(bool: Graph, input_1: Graph, input_2: Graph) -> Graph: ...

def composition_kaleidoscope_internal(composition: Graph, segments: Graph, rotation: Graph, warp: Graph, warp_frequency: Graph) -> Graph: ...

def composition_l_curve_internal(composition: Graph, l_curve: Graph) -> Graph: ...

def composition_lightness_threshold_internal(composition: Graph, threshold: Graph) -> Graph: ...

def composition_linear_transform_internal(composition: Graph, entry_0_0: Graph, entry_0_1: Graph, entry_0_2: Graph, entry_0_3: Graph, entry_1_0: Graph, entry_1_1: Graph, entry_1_2: Graph, entry_1_3: Graph, entry_2_0: Graph, entry_2_1: Graph, entry_2_2: Graph, entry_2_3: Graph, entry_3_0: Graph, entry_3_1: Graph, entry_3_2: Graph, entry_3_3: Graph) -> Graph: ...

def composition_liquify_internal(composition: Graph, amplitude: Graph, frequency: Graph) -> Graph: ...

def composition_median_internal(composition: Graph, kernel_size: Graph) -> Graph: ...

def composition_monet_women_with_parasol_internal() -> Graph: ...

def composition_morphological_max_internal(composition: Graph, dimension: Graph) -> Graph: ...

def composition_morphological_min_internal(composition: Graph, dimension: Graph) -> Graph: ...

def composition_negative_internal(composition: Graph) -> Graph: ...

def composition_opacity_scale_internal(composition: Graph, scale: Graph) -> Graph: ...

def composition_painter_internal(painter: Graph) -> Graph: ...

def composition_passthrough_internal(value: Graph) -> Graph: ...

def composition_pixelate_internal(composition: Graph, pixel_size: Graph) -> Graph: ...

def composition_point_effect_shader_internal(composition: Graph, function_body: Graph, helpers: Graph, effect_center_point: Graph, effect_radius: Graph, inputs: Graph) -> Graph: ...

def composition_r_g_b_curve_internal(composition: Graph, r_curve: Graph, g_curve: Graph, b_curve: Graph) -> Graph: ...

def composition_render_to_image_internal(composition: Graph) -> Graph: ...

def composition_rotate180_internal(composition: Graph) -> Graph: ...

def composition_rotate90_clockwise_internal(composition: Graph) -> Graph: ...

def composition_rotate90_counter_clockwise_internal(composition: Graph) -> Graph: ...

def composition_s_a_m3_image_internal(composition: Graph, prompt: Graph, positive_points: Graph, negative_points: Graph) -> Graph: ...

def composition_saturation_adjust_internal(composition: Graph, scale: Graph) -> Graph: ...

def composition_scanlines_internal(composition: Graph, size: Graph, beam_power: Graph, line_offset: Graph, intensity: Graph) -> Graph: ...

def composition_segment_internal(composition: Graph, prompt: Graph, positive_points: Graph, negative_points: Graph) -> Graph: ...

def composition_sharpen_internal(composition: Graph, radius: Graph, strength: Graph) -> Graph: ...

def composition_sobel_edge_detection_internal(composition: Graph) -> Graph: ...

def composition_spacial_effect_shader_internal(composition: Graph, function_body: Graph, helpers: Graph, max_displacement: Graph, inputs: Graph) -> Graph: ...

def composition_swirl_internal(composition: Graph, center: Graph, radius: Graph, amount: Graph) -> Graph: ...

def composition_target_white_kelvin_internal(composition: Graph, kelvin: Graph) -> Graph: ...

def composition_to_ok_lab_hist_internal(composition: Graph) -> Graph: ...

def composition_transform_internal(composition: Graph, transform: Graph) -> Graph: ...

def composition_vibrance_adjustment_internal(composition: Graph, strength: Graph) -> Graph: ...

def composition_vignette_internal(composition: Graph, center: Graph, radius_x: Graph, radius_y: Graph, softness: Graph, strength: Graph) -> Graph: ...

def composition_zoom_blur_internal(composition: Graph, center: Graph, strength: Graph, falloff: Graph, effect_radius: Graph) -> Graph: ...

def curve_evaluate_internal(curve: Graph, input: Graph) -> Graph: ...

def curve_gamma_internal(gamma: Graph) -> Graph: ...

def curve_identity_internal() -> Graph: ...

def curve_pivoted_sigmoid_internal(pivot: Graph, slope: Graph) -> Graph: ...

def curve_s_curve_internal(pivot: Graph, slope: Graph, toe: Graph, shoulder: Graph) -> Graph: ...

def dictionary_create_internal() -> Graph: ...

def file_convert_image_to_bmp_internal(image_bytes: Graph) -> Graph: ...

def file_convert_image_to_heic_internal(image_bytes: Graph, quality: Graph) -> Graph: ...

def file_convert_image_to_jpeg_internal(image_bytes: Graph, quality: Graph) -> Graph: ...

def file_convert_image_to_png_internal(image_bytes: Graph) -> Graph: ...

def file_convert_image_to_tiff_internal(image_bytes: Graph) -> Graph: ...

def file_convert_image_to_web_p_internal(image_bytes: Graph, quality: Graph) -> Graph: ...

def file_convert_video_to_animated_web_p_internal(video_bytes: Graph) -> Graph: ...

def file_convert_video_to_gif_internal(video_bytes: Graph, frame_rate: Graph) -> Graph: ...

def file_convert_video_to_m_p4_internal(video_bytes: Graph) -> Graph: ...

def file_convert_video_to_web_m_internal(video_bytes: Graph) -> Graph: ...

def fill_custom_internal(function_body: Graph, helpers: Graph, inputs: Graph) -> Graph: ...

def fill_solid_internal(color: Graph) -> Graph: ...

def float_add_internal(float1: Graph, float2: Graph) -> Graph: ...

def float_add_to_dictionary_internal(dictionary: Graph, key: Graph, value: Graph) -> Graph: ...

def float_cos_internal(angle: Graph) -> Graph: ...

def float_divide_internal(float1: Graph, float2: Graph) -> Graph: ...

def float_equals_internal(float_1: Graph, float_2: Graph) -> Graph: ...

def float_greater_than_internal(float_1: Graph, float_2: Graph) -> Graph: ...

def float_greater_than_or_equal_internal(float_1: Graph, float_2: Graph) -> Graph: ...

def float_if_internal(bool: Graph, input_1: Graph, input_2: Graph) -> Graph: ...

def float_lerp_internal(x: Graph, float1: Graph, float2: Graph) -> Graph: ...

def float_less_than_internal(float_1: Graph, float_2: Graph) -> Graph: ...

def float_less_than_or_equal_internal(float_1: Graph, float_2: Graph) -> Graph: ...

def float_max_internal(float1: Graph, float2: Graph) -> Graph: ...

def float_min_internal(float1: Graph, float2: Graph) -> Graph: ...

def float_multiply_internal(float1: Graph, float2: Graph) -> Graph: ...

def float_passthrough_internal(value: Graph) -> Graph: ...

def float_pow_internal(float1: Graph, float2: Graph) -> Graph: ...

def float_round_to_int_internal(float: Graph) -> Graph: ...

def float_sin_internal(angle: Graph) -> Graph: ...

def float_square_root_internal(number: Graph) -> Graph: ...

def float_squared_internal(number: Graph) -> Graph: ...

def float_subtract_internal(float1: Graph, float2: Graph) -> Graph: ...

def image_from_byte_list_internal(bytes: Graph) -> Graph: ...

def image_to_byte_list_internal(image: Graph) -> Graph: ...

def int_abs_internal(number: Graph) -> Graph: ...

def int_add_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_add_to_dictionary_internal(dictionary: Graph, key: Graph, value: Graph) -> Graph: ...

def int_equals_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_greater_than_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_greater_than_or_equal_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_if_internal(bool: Graph, input_1: Graph, input_2: Graph) -> Graph: ...

def int_less_than_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_less_than_or_equal_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_max_internal(int1: Graph, int2: Graph) -> Graph: ...

def int_min_internal(int1: Graph, int2: Graph) -> Graph: ...

def int_multiply_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_passthrough_internal(value: Graph) -> Graph: ...

def int_subtract_internal(int_1: Graph, int_2: Graph) -> Graph: ...

def int_to_float_internal(int: Graph) -> Graph: ...

def monet_network_download_u_r_l_from_asset_i_d_internal(asset_id: Graph) -> Graph: ...

def not_internal(bool: Graph) -> Graph: ...

def null_value_internal() -> Graph: ...

def ok_lab_color_from_components_internal(l: Graph, a: Graph, b: Graph) -> Graph: ...

def ok_lab_hist_lightness_quantile_internal(hist: Graph, quantile: Graph) -> Graph: ...

def ok_lab_to_r_g_b_internal(ok_lab: Graph, color_profile: Graph) -> Graph: ...

def or_internal(bool1: Graph, bool2: Graph) -> Graph: ...

def painter_add_ellipse_with_render_style_internal(painter: Graph, center: Graph, dimensions: Graph, rotation: Graph, render_style: Graph, instances: Graph) -> Graph: ...

def painter_add_path_with_render_style_internal(painter: Graph, path: Graph, render_style: Graph, instances: Graph) -> Graph: ...

def painter_add_rectangle_with_render_style_internal(painter: Graph, center: Graph, dimensions: Graph, rotation: Graph, render_style: Graph, instances: Graph) -> Graph: ...

def painter_new_internal(color_profile: Graph) -> Graph: ...

def path_cardinal_cubic_to_point_internal(path: Graph, point: Graph, tension: Graph) -> Graph: ...

def path_catmull_rom_to_point_internal(path: Graph, point: Graph) -> Graph: ...

def path_line_to_point_internal(path: Graph, point: Graph) -> Graph: ...

def path_move_to_point_internal(path: Graph, point: Graph) -> Graph: ...

def path_new_internal() -> Graph: ...

def pi_internal() -> Graph: ...

def point2f_distance_internal(lhs: Graph, rhs: Graph) -> Graph: ...

def point2f_from_components_internal(x: Graph, y: Graph) -> Graph: ...

def point2i_distance_internal(lhs: Graph, rhs: Graph) -> Graph: ...

def point2i_from_components_internal(x: Graph, y: Graph) -> Graph: ...

def r_g_b_a_color_add_to_dictionary_internal(dictionary: Graph, key: Graph, value: Graph) -> Graph: ...

def r_g_b_a_color_from_components_internal(r: Graph, g: Graph, b: Graph, a: Graph) -> Graph: ...

def r_g_b_a_color_passthrough_internal(value: Graph) -> Graph: ...

def r_g_b_color_add_to_dictionary_internal(dictionary: Graph, key: Graph, value: Graph) -> Graph: ...

def r_g_b_color_from_components_internal(r: Graph, g: Graph, b: Graph) -> Graph: ...

def r_g_b_color_passthrough_internal(value: Graph) -> Graph: ...

def r_g_b_to_ok_lab_internal(rgb: Graph, color_profile: Graph) -> Graph: ...

def render_style_brush_and_fill_internal(brush: Graph, fill: Graph) -> Graph: ...

def render_style_brush_only_internal(brush: Graph) -> Graph: ...

def render_style_fill_only_internal(fill: Graph) -> Graph: ...

def sequence_adjust_speed_internal(sequence: Graph, factor: Graph) -> Graph: ...

def sequence_composition_at_time_internal(sequence: Graph, time: Graph) -> Graph: ...

def sequence_concatenate_internal(sequence_1: Graph, sequence_2: Graph) -> Graph: ...

def sequence_duration_internal(sequence: Graph) -> Graph: ...

def sequence_from_composition_and_duration_internal(composition: Graph, duration: Graph) -> Graph: ...

def sequence_from_u_r_l_internal(url: Graph) -> Graph: ...

def sequence_graph_internal(duration: Graph, time: Graph, frame: Graph) -> Graph: ...

def sequence_grayscale_internal(sequence: Graph) -> Graph: ...

def sequence_passthrough_internal(value: Graph) -> Graph: ...

def sequence_reverse_internal(sequence: Graph) -> Graph: ...

def sequence_to_mp4_internal(sequence: Graph, frame_rate: Graph) -> Graph: ...

def sequence_trim_back_internal(sequence: Graph, amount: Graph) -> Graph: ...

def sequence_trim_front_internal(sequence: Graph, amount: Graph) -> Graph: ...

def string_if_internal(bool: Graph, input_1: Graph, input_2: Graph) -> Graph: ...

def transform2_identity_internal() -> Graph: ...

def transform2_if_internal(bool: Graph, input_1: Graph, input_2: Graph) -> Graph: ...

def transform2_rotate_internal(transform: Graph, angle: Graph) -> Graph: ...

def transform2_scale_internal(transform: Graph, scale: Graph) -> Graph: ...

def transform2_to_list_internal(item: Graph) -> Graph: ...

def transform2_translation_internal(transform: Graph, translation: Graph) -> Graph: ...

def upload_byte_list_internal(bytes: Graph, url: Graph, content_type: Graph) -> Graph: ...

def upload_file_path_internal(path: Graph, url: Graph, content_type: Graph) -> Graph: ...

def vector2_int_to_vector2_float_internal(vector: Graph) -> Graph: ...

def vector2f_add_internal(lhs: Graph, rhs: Graph) -> Graph: ...

def vector2f_add_to_dictionary_internal(dictionary: Graph, key: Graph, value: Graph) -> Graph: ...

def vector2f_from_components_internal(x: Graph, y: Graph) -> Graph: ...

def vector2f_normalize_internal(vector: Graph) -> Graph: ...

def vector2f_passthrough_internal(value: Graph) -> Graph: ...

def vector2f_scalar_multiply_internal(vector: Graph, scalar: Graph) -> Graph: ...

def vector2f_x_internal(vector: Graph) -> Graph: ...

def vector2f_y_internal(vector: Graph) -> Graph: ...

def vector2i_add_internal(lhs: Graph, rhs: Graph) -> Graph: ...

def vector2i_add_to_dictionary_internal(dictionary: Graph, key: Graph, value: Graph) -> Graph: ...

def vector2i_from_components_internal(x: Graph, y: Graph) -> Graph: ...

def vector2i_passthrough_internal(value: Graph) -> Graph: ...

def vector2i_to_vector2f_internal(vector: Graph) -> Graph: ...

def vector2i_x_internal(vector: Graph) -> Graph: ...

def vector2i_y_internal(vector: Graph) -> Graph: ...

def vector3f_add_internal(lhs: Graph, rhs: Graph) -> Graph: ...

def vector3f_from_components_internal(x: Graph, y: Graph, z: Graph) -> Graph: ...

def vector3f_normalize_internal(vector: Graph) -> Graph: ...

def vector3f_x_internal(vector: Graph) -> Graph: ...

def vector3f_y_internal(vector: Graph) -> Graph: ...

def vector3f_z_internal(vector: Graph) -> Graph: ...

def xor_internal(bool1: Graph, bool2: Graph) -> Graph: ...
